### ISSUE TITLE
setWindowMode功能

### ISSUE THREAD

**Issue by Particaly** [kihlh/hmc-win32#14]
有个疑惑点请教一下，文件source/CPP/Main.cpp 1733行，移动窗口的功能，如果我确实需要将窗口移动到左上角[0, 0]处, 此处的x, y是否不需要做判0验证

**Comment by kihlh** [comment]
屏幕位置中是不存在x=0,y=0 的  如果需要挪动到左上角因当为[1,1] ,第一个窗口像素所处的位置便是[1,1]坐标

x=0,y=0将被直接视为调整窗口宽度和高度 [x,y]坐标位置会保持不动
在hmc js脚本中也直接将  null  void 0 等空值 视为了0

**Comment by Particaly** [comment]
明白了，感谢解答！
