### ISSUE TITLE
鼠标监听有数据丢失

### ISSUE THREAD

**Issue by selang** [kihlh/hmc-win32#17]
鼠标左键按下能监听到,但是抬起就没监听到了.鼠标右键和鼠标中键的点击没有监听到.

**Comment by kihlh** [comment]
是的  我当年设计的时候没有想到这个功能，
并不是数据丢失而是他不支持

**所以他不具备有这个功能，我近期添加一下**

**Comment by kihlh** [comment]
在 https://github.com/kihlh/hmc-win32/commit/9df8314a660432d9c4176bde53da2a42ed0da383  中已经解决此问题 再下次版本更新时发布

**Comment by kihlh** [comment]
在1.3.9 版本已上线
