### ISSUE TITLE
希望能兼容高版本的node现在高版本无法使用require

### ISSUE THREAD

**Issue by leekay0032** [kihlh/hmc-win32#18]
希望能兼容高版本的node现在高版本无法使用require
let HMC = require("hmc-win32");
改为
import HMC from "hmc-win32"
后出现
X [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/hmc-win32@1.3.7/node_modules/hmc-win32/bin/HMC_x64.node

    node_modules/.pnpm/hmc-win32@1.3.7/node_modules/hmc-win32/index.js:730:23:
      730 │         return require("./bin/HMC_x64.node");
          ╵                        ~~~~~~~~~~~~~~~~~~~~

X [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/hmc-win32@1.3.7/node_modules/hmc-win32/bin/HMC_x86.node

    node_modules/.pnpm/hmc-win32@1.3.7/node_modules/hmc-win32/index.js:728:23:
      728 │         return require("./bin/HMC_x86.node");
          ╵                        ~~~~~~~~~~~~~~~~~~~~

在_require_bin方法中也是使用的require，导致无法在高版本node中使用

**Comment by kihlh** [comment]
事实上我在很早以前就做了require和import的互相兼容，但是并不能成功，因为.node是个二进制他无法被import导入，node在这方面很糟糕，在我刚刚我也浏览了几个几K星星的库，他们也没有做到import兼容，如果您可以提供相关的成功案例我会很乐意修复这个问题
