### ISSUE TITLE
没有最基本的findWindow函数？

### ISSUE THREAD

**Issue by jbeetle** [kihlh/hmc-win32#19]
想换掉koffi，发现居然没有
 const FindWindowW = lib.stdcall('FindWindowW', 'int', ['str16', 'str16']);
这是windows api最基础的api呀

**Comment by kihlh** [comment]
确实不支持，

以前是有的，但是很容易失败还留着是对用户的不负责

因为编码特殊性，等我有空把一个大佬手撸的编码库应用进去就能支持了

或者看看能不能靠node自带的编码转为utf16再转为指针使用了

**Comment by kihlh** [comment]
近期加上

**Comment by jbeetle** [comment]
期待

**Comment by kihlh** [comment]
1.3.8 中已经发布
![image](https://github.com/kihlh/hmc-win32/assets/62889891/084f70f1-8ae0-4f6c-8792-0b879aeab0b7)

**Comment by jbeetle** [comment]
good!
