### ISSUE TITLE
建议将 putSystemVariable 、putUserVariable方法名改成 setXXX

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#25]
建议将 putSystemVariable 、putUserVariable方法名改成 setXXX
参考c# api
https://learn.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-8.0

**Comment by kihlh** [comment]
我加个映射
，这个是微软vc++的起名方式

**Comment by kihlh** [comment]
已处理 下个版本中更新

**Comment by kihlh** [comment]
1.4.0已经解决此问题
