### ISSUE TITLE
getProcessName、getProcessidFilePath获取不到系统和管理员进程的信息

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#27]
getProcessName、getProcessidFilePath获取不到系统和管理员进程的信息

**Comment by xianyunleo** [comment]
当前程序已经是管理员身份运行了

**Comment by kihlh** [comment]
此问题已经解决 将在下个版本中发布
![image](https://github.com/kihlh/hmc-win32/assets/62889891/e636830a-9d00-4637-9eac-e46418a1b46d)
![image](https://github.com/kihlh/hmc-win32/assets/62889891/83123c26-a277-4b3a-a78c-dcf9fb9bd90f)

**Comment by kihlh** [comment]
> getProcessName、getProcessidFilePath获取不到系统和管理员进程的信息
此问题已经在1.4.0解决

获取不到则说明这是个内核进程或者服务进程 或者被权限保护了，可以使用内核快照找到名称
getAllProcessListNt2   `最高的内核权限`
getAllProcessList2Snp   `进程快照树 大概率有`  这个有个局限在于 如果可执行文件是32位系统是64位将获取不到64位进程信息
