### ISSUE TITLE
修复 getDetailsProcessList，getProcessList，getProcessidFilePath，getProcessName 对于 内核进程/ 服务进程 无效

### ISSUE THREAD

**Issue by kihlh** [kihlh/hmc-win32#28]

**Comment by kihlh** [comment]
使用三种方式对主进程的镜像文件进行获取 

![image](https://github.com/kihlh/hmc-win32/assets/62889891/44f830f4-2ce4-4f1c-8fce-bc5a246a0005)

![image](https://github.com/kihlh/hmc-win32/assets/62889891/e63123ca-3fd7-468d-a026-110920e3bf34)

**Comment by kihlh** [comment]
内核进程 ntoskrnl.exe  的进程几乎都是无权限访问的，在进程镜像中显示由于win32 进程是4的倍数 所以 4 大概率是ntoskrnl.exe
而 80以内大概率都是内核程序 获取0-80的快照非常快，所以从快照中查找此进程特征进行判断 第一次出现的无名 L"System" 是ntoskrnl.exe  而ntoskrnl.exe路径是固定的 "C:\\Windows\\System32\\ntoskrnl.exe" 
那么现在我们就可以确认 80以内 父进程是ntoskrnl.exe的进程也是ntoskrnl.exe

至于 Registry 这个无从查起因为任务管理器也找不到此应用归属

![image](https://github.com/kihlh/hmc-win32/assets/62889891/86d65d63-6f4d-459e-a5a2-0c71fa4362a5)

**Comment by kihlh** [comment]
放弃使用  GetModuleBaseNameA api

**Comment by xianyunleo** [comment]
"System"等内核进程，可以参考PowerShell或C#，只提供Name，不提供Path
`Get-Process -Id 4`
`(Get-Process -Id 4).Name`
`(Get-Process -Id 4).Path`

查看属性定义
`Get-Process| Get-Member`

@kihlh

**Comment by kihlh** [comment]
> "System"等内核进程，可以参考PowerShell或C#，只提供Name，不提供Path `Get-Process -Id 4` `(Get-Process -Id 4).Name` `(Get-Process -Id 4).Path`
> 
> 查看属性定义 `Get-Process| Get-Member`
> 
> @kihlh

不考虑调用shell获取，因为太慢了而且困难从从，**此问题已经解决了** 现在只需要格式化几个内核程序的实际路径就完成了
![image](https://github.com/kihlh/hmc-win32/assets/62889891/f9c4fc54-4c80-4401-a20c-4d0d13a7045c)

**Comment by xianyunleo** [comment]
你误解了我的意思了。我的意思是，内核进程的Path就直接返回空字符串好了。C#的API就是这么做的。 @kihlh

**Comment by kihlh** [comment]
此需求被合并到 #30
