### ISSUE TITLE
setFocus 无效

### ISSUE THREAD

**Issue by wuchuguang** [kihlh/hmc-win32#3]
hcm.setWindowFocus(handle)
和
handle.setFucus()
都无效果。

**Comment by wuchuguang** [comment]
setTile正常。

**Comment by kihlh** [comment]
问题存在 
c++自带的winapi   存在概率性复现 
下个版本解决

**Comment by kihlh** [comment]
win 自带对其他窗口的限制，已解决 但是不是每种窗口都能成功 因为这个简单的小功能比想象中复杂

系统限制哪些进程可以设置前台窗口。 仅当下列条件之一为 true 时，进程才能设置前台窗口：

此过程是前台进程。
进程由前台进程启动。
进程收到了最后一个输入事件。
没有前台进程。
正在调试该过程。
前台进程不是新式应用程序或“开始”屏幕。
前台未锁定， (请参阅 [LockSetForegroundWindow](https://learn.microsoft.com/zh-cn/windows/desktop/api/winuser/nf-winuser-locksetforegroundwindow)) 。
前台锁定超时已过期， (在 [SystemParametersInfo](https://learn.microsoft.com/zh-cn/windows/desktop/api/winuser/nf-winuser-systemparametersinfoa)) 中看到SPI_GETFOREGROUNDLOCKTIMEOUT。
没有活动菜单。

**Comment by kihlh** [comment]
如果需要现在使用直接替换两个.node  文件就行了 小更新一般推送到npm
