### ISSUE TITLE
API 增改

### ISSUE THREAD

**Issue by kihlh** [kihlh/hmc-win32#30]
###  需要新增的API
- [x] getAllProcessList  `异步`  获取进程列表（枚举）  _枚举是最快的也不受应用是32位系统64位导致无法枚举到 但是信息不够细_
   - pid 进程id
   - name 由镜像路径解析
   - path 镜像路径
- [x] getAllProcessListSync `同步`  获取进程列表（枚举）
- [x] getAllProcessListSnp   `异步`  获取进程列表 (快照)
   - _请注意 如果可执行文件是32位而系统是64位将获取不到64位进程的信息_
   - pid 进程id
   - name 由镜像路径解析
   - ppid 父进程id
   - `cntThreads`  `cntUsage`  `dwFlags`  `dwSize`  `pcPriClassBase`  `th32DefaultHeapID`  `th32ModuleID` 
- [x] getAllProcessListSnpSync `同步`  获取进程列表 (快照) 
- [x] getAllProcessListNt   `异步`  获取进程列表 (内核)
   - pid 进程id
   - name 软件名称
   - `BasePriority`  `NextEntryOffset`  `NumberOfThreads`  `PagefileUsage`  `pcPriClassBase`  `PeakPagefileUsage`  `PeakWorkingSetSize`   `QuotaNonPagedPoolUsage`   `Reserved [1-6]` 
- [x] getAllProcessListNtSync    `同步`  获取进程列表 (内核)
- [x] getProcessCpuUsage   `异步`  获取进程占用的cpu
- [x] getProcessCommand    `异步`  获取进程的命令行
- [x] getProcessCommandSync    `同步`  获取进程的命令行
- [x] getProcessCwd    `异步`  获取进程的工作目录
- [x] getProcessCwdSync    `同步`  获取进程的工作目录
- [x] getProcessNameSnpSync    `同步`  获取进程的名称(快照)
- [x] getProcessNameSnp    `异步`  获取进程的命令行(快照)
- [x] getProcessNameNtSync    `同步`  获取进程的名称(内核)
- [x] getProcessNameNt    `异步`  获取进程的命令行(内核)
- [x] getProcessNameSync    `同步`  获取进程的名称(正常)
- [x] getProcessName    `异步`  获取进程的命令行(正常)
- [ ] 键鼠操作应当有属于自己的延迟
- [ ] 新增全局快捷键注册
- [ ] **mouseHook** 增加一个移动方向
- [x] **setLimitMouseRange** 限制鼠标可移动范围
- [x] **hasLimitMouseRangeWorker**  是否 正在调用着 限制鼠标可移动范围的线程
- [x] **stopLimitMouseRangeWorker**  提前结束限制鼠标可移动范围 一旦调用则立即解锁 返回的布尔是解锁线程是否成功
- [ ] isFocusWindowFullScreen 判断是否存在尺寸铺满整个屏幕的软件
- [ ] isFullScreen 判断是否处于全屏模式 【已添加未暴露】
- [ ] clearTrash 清空回收站 【已添加未暴露】
- [ ] setConversionStatus 切换输入法 【已添加未暴露】
- [ ] getWindowHwndStatus 获取窗口相关句柄信息 例如子窗主窗根窗邻窗。。。 【已添加未暴露】
- [ ] hmc_Keyboard 低级的键盘监听重构【已添加未暴露】
- [ ] beep 播放win警告的声音
- [ ] copyFile   复制文件/文件夹(调用的资源管理器)
- [ ] moveFile    移动文件/文件夹(调用的资源管理器)
- [ ] winRunApplication   使用win自带的运行 执行程序
- [ ] getThumbnailPngFile   获取缩略图
- [ ] SetFolderIcon   设置文件夹夹的缩略图
- [ ] setSystemStartup   添加自启动到注册表自启动里
- [ ] setSystemStartupService   添加自启（服务）
- [ ] setStartup   添加软件自启动
- [ ] removeStartup   移除软件自启动
- [ ] removeStartupService   移除软件自启动（服务）
- [ ] hasStartup   判断软件自启动
- [ ] hasStartupService   判断软件自启动（服务）
- [ ] SelectFolderV1    选择文件夹 （古老的小框选择器 无法指定路径的那种）
- [ ] SelectFolder   选择文件夹（单选）
- [ ] SelectFolders   选择文件夹(多选)
- [ ] SelectFiles   选择文件 （多个文件）
- [ ] SelectFile   选择文件 （单个文件）
- [ ] SelectFiles   选择文件 （多个文件）
- [ ] 特殊键盘快捷键 例如ctrl + c + c 500ms内
- [ ] **tray** 托盘api支持 https://github.com/kihlh/hmc-win32/issues/38

###  需要新增的异步io
- [ ] getAllWindows
- [ ] enumProcessHandle 
- [ ] enumAllProcessHandle 
- [ ] getProcessNameList 
- [ ] getProcessThreadList 
- [x] getProcessParentProcessID 
- [ ] getModulePathList
- [x] getProcessList 
- [x] getAllProcessList
- [ ] getSubProcessID

### 更名计划 (**原api不受影响**)
- [x] lookHandleGetTitle          -> getWindowTitle
- [x] lookHandleSetTitle           -> setWindowTitle
- [x] getHandleProcessID         -> getWindowProcess
- [x] getProcessHandle             -> getProcessWindow
- [x] lookHandleShowWindow  -> setShowWindow
- [x] isHandleWindowVisible     -> isWindowVisible
- [x] lookHandleCloseWindow  -> closeWindow
- [x] windowJitter                      -> setWindowShake
- [x] hasWindowTop                  -> isWindowTop
- [x] getProcessidFilePath          -> getProcessFilePath
- [x] getDetailsProcessNameList  -> findProcess

### api 变更
- [x] getDetailsProcessList           从定向到 getAllProcessListSync( <pid> <name> <path> )

### API 重构
 来自  https://github.com/kihlh/hmc-win32/issues/43
#### 删除
- [x] getStringRegKey  删除
- [x] hasRegistrKey  删除
- [x] setRegistrKey  删除
- [x] createPathRegistr  删除
- [x] enumRegistrKey  删除
- [x] getRegistrBuffValue  删除
- [x] removeStringRegKeyWalk  删除
- [x] removeStringRegKey  删除
- [x] removeStringRegValue  删除
- [x] setRegistrDword  删除
- [x] setRegistrQword  删除
- [x] getRegistrDword  删除
- [x] getRegistrQword  删除
#### 新增
- [x] getRegistrValue 新增
- [x] setRegistrValue 新增
- [x] removeRegistrFolder 新增
- [x] removeRegistrValue 新增
- [x] createRegistrFolder 新增
- [x] getRegistrFolderStat 新增
- [x] getRegistrValueStat 新增
- [x] getRegistrBuffValue 新增

**Comment by yhtt2020** [comment]
大佬辛苦了

**Comment by kihlh** [comment]
更新动作太大  此表无意义  作废
