### ISSUE TITLE
鼠标相关api的几个问题

### ISSUE THREAD

**Issue by kihlh** [kihlh/hmc-win32#33]
- [x] 1. 当用户设置屏幕特别刁钻时候 比如右屏当作屏幕用的时候会导致getMouseMovePoints 获取异常，此问题为winapi问题 
  - 此问题已经解决 通过获取屏幕方式四指标进行计算，可以得出真实的负坐标
![image](https://github.com/kihlh/hmc-win32/assets/62889891/2f7d46ad-50a6-479d-9831-c89a4bd0b222)
- [x] 2. 新增api .getCursorPos()
  - 已经添加 尚未暴露接口
- [x] 3.  setCursorPos 新增一个必达布尔 例如 500ms之内如果鼠标停止了移动再次执行坐标移动，以此达到必达的目的
  - 此需求已经提供帮助 在12. 目前设想 当必达激活返回的将会是一个Promise对象
- [x] 4.  mouseHook 防抖从 0-400000000 变更到 -400000000  =>   400000000 
  - 【重构版本移除了此属性】
- [x] 5.  键鼠Hook 有个很该死延时 延迟了2ms不知道这个延时哪里来的 可能导致多次hook时候出现漂移和卡顿
  -  【并未发现此延迟对键鼠的影响但是发现cpu占用偏高 此问题被13条解决】
- [x] 6.  mouseHook有个概率复现问题  释放hook函数以后无法重新建立监听
  -  目前未找到此问题在哪 等cpp接口写完了再排除
- [ ] 7. 新增全局快捷键注册
  - 等待添加
- [x] 8. asyncCall any Hook 每次执行一次hook都要重新创建一次线程来异步处理 这个可能会出现不必要的性能消耗 虽然他微乎其微
  - 使用了静态内存块进行128个历史记录的缓冲，如果满了才会进行动态开辟内存，以此节省因为开辟内存导致的纳秒级消耗
- [ ] 9. 键鼠操作应当有属于自己的延迟
  - 此项可以在js脚本中处理
- [x] 10. setCursorPos 在双屏下可能会导致无法成功，此问题为winapi问题  尝试修复
  - 未发现此问题对实际存在的屏幕坐标有影响，使用模拟鼠标也无效，这意味着光标只能在有屏幕的坐标中存在，并不能随意定义位置
- [ ] 11. mouseHook增加一个移动方向
  - 此功能可以在js脚本中插槽
- [x] 12.新增api getLastInputInfo (获取最后输入时间) 例如鼠标 键盘
  - 已支持 并且3.的必达功能也会使用到此api
- [x] 13.使用 GetMessage激活法 代替原先的 PeekMessage 激活法 可以节省CPU占用 也能激活键鼠低级HOOK回调
  - 已经解决了此问题  
### 重要： 重构 mouseHook，KeyboardHook
  - KeyboardHook 需要重新设计结构 
  - mouseHook 数据结构 数据存储机制 推送机制  已经重新设计 已经可以做到处理hook的过程非常节省性能

**Comment by yhtt2020** [comment]
感谢大佬，神速。

**Comment by kihlh** [comment]
此issues 未完成的需求 被合并到 https://github.com/kihlh/hmc-win32/issues/30
