### ISSUE TITLE
getDetailsProcessList返回数据不正确

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#34]
v1.4.0，getDetailsProcessList()返回数组，但是对象是空的。其他api可能也有类似问题。

**Comment by kihlh** [comment]
> v1.4.0，getDetailsProcessList()返回数组，但是对象是空的。其他api可能也有类似问题。
抱歉 我的疏忽  加了个处理路径的map 忘了push

**Comment by kihlh** [comment]
已经修复并发布在1.4.1
