### ISSUE TITLE
在win11 上getTrayList返回空列表

### ISSUE THREAD

**Issue by yhtt2020** [kihlh/hmc-win32#36]
![image](https://github.com/kihlh/hmc-win32/assets/1708510/842e7957-3041-422c-9b35-c42b1e29032b)
尝试重启，均无效
无报错
操作系统：win11
其他系统未测试

**Comment by kihlh** [comment]
这api居然有人用😂，
我研究下，
写这个的时候win11还没出现😂😂😂

**Comment by kihlh** [comment]
我记得win11 句柄类名称变了，估计有重构

**Comment by kihlh** [comment]
win11 在22621.1000版本之后 将系统托盘替换为 XAML 应用，也不再带有托盘图标句柄，目前唯一的方案只有读取内存了，但是这样做不安全，所以此问题无法解决
