### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#4]
![12](https://user-images.githubusercontent.com/104482255/224940089-d8c0ffec-6a3e-4d6c-9dd6-002bb9693685.png)

![image](https://user-images.githubusercontent.com/104482255/224940329-da4d386c-1f03-4b78-9021-2197985d1765.png)

electron项目

electron，v22.3.2
electron/remote，v2.0.9

node，v16.19.1

**Comment by kihlh** [comment]
可能是不支持的构架 他只支持win
 process.arch 是什么

![image](https://user-images.githubusercontent.com/62889891/225057283-3e1c6bb8-ec70-41ca-8c50-ec84eebd2719.png)

**Comment by xianyunleo** [comment]
> 可能是不支持的构架 他只预编译了常见的 win x32 和 x64 process.platform 和 process.arch 是什么
> 
> ![image](https://user-images.githubusercontent.com/62889891/225057283-3e1c6bb8-ec70-41ca-8c50-ec84eebd2719.png)

正常的Windows x64，而且你这串代码我单独提出来，是没问题了，但是跑在项目里就会有问题，要不，我给你发个最小demo?

**Comment by kihlh** [comment]
是否 使用了打包工具 比如esbuild或者webpack , ncc
二进制模块一般是不能被打包的 所以我将其他无用内容都从模块移除了

**Comment by kihlh** [comment]
electron 一般会设置排除二进制模块的打包，或者自定义二进制位置 比如我的用法是单独存放在软件根目录

**Comment by xianyunleo** [comment]
> 是否 使用了打包工具 比如esbuild或者webpack , ncc 二进制模块一般是不能被打包的 所以我将其他无用内容都从模块移除了

用了webpack，一般模块都是npm安装后直接用，不太明白你这个模块要怎么使用

**Comment by kihlh** [comment]
webpack里面设置打包排除 hmc-win32 模块就行了

因为.node 并不是代码 他不会被默认打包进去
