### ISSUE TITLE
添加Windows11 窗口标题栏Snap支持

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#40]
https://learn.microsoft.com/zh-cn/windows/apps/desktop/modernize/apply-snap-layout-menu

**Comment by kihlh** [comment]
貌似 Electron自带这个API 在v13稳定版以后

**Comment by xianyunleo** [comment]
> 貌似 Electron自带这个API 在v13稳定版以后

那得用electron自带的titlebar，自己画的titlebar不支持

**Comment by xianyunleo** [comment]
electron 窗口 HWND 相关 api
`win.getNativeWindowHandle()`
Returns `Buffer `- The platform-specific handle of the window.
The native type of the handle is HWND on Windows

**Comment by kihlh** [comment]
目前winapi并未提供api调用此功能 ，所以我只想的到两个方法 一个是危险的一个是简单粗暴的，但不涉及系统apihook，而且窗口消息在不使用汇编hook的前提下 信息是不能被获取到的 不知道有没有大佬有更好的建议

使用穿透性的子窗口获取与返回消息 如图所示
![image](https://github.com/kihlh/hmc-win32/assets/62889891/ad05005c-6fd3-4764-b7dc-2208c01e7e2d)

使用win+z调用
![image](https://github.com/kihlh/hmc-win32/assets/62889891/51b643de-99e5-4f78-8ea1-c28bb78c3e9c)

至于真实的Snap winapi是哪个暂时没空探索

**Comment by xianyunleo** [comment]
https://github.com/grassator/win32-window-custom-titlebar
不知道这个项目对你来说是否有帮助

**Comment by kihlh** [comment]
> https://github.com/grassator/win32-window-custom-titlebar 不知道这个项目对你来说是否有帮助

![image](https://github.com/kihlh/hmc-win32/assets/62889891/40bfcfeb-1d12-4c74-a81d-30a582e67346)

他这里也事对自己归属权的窗口进行返回 信息给api

但是很遗憾 窗口的回调在不hook的前提下是很难接管的，electron只具备了获取值并不具备返回值的功能，我的建议是使用隐藏的窗口标题头，三大按钮和普通win位置保持一致 这样子同样能够激活 Snap

**Comment by xianyunleo** [comment]
由于太复杂，这个功能就先这样吧
