### ISSUE TITLE
getProcessParentProcessID 返回了空数组

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#41]

**Comment by kihlh** [comment]
如何调用的  是什么类型的程序 能用ark截图下进程嘛  和调用方法嘛

**Comment by xianyunleo** [comment]
1.3.9没问题。1.4.1有问题

**Comment by xianyunleo** [comment]
1.3.9没问题。1.4.3有问题

**Comment by kihlh** [comment]
我研究下 1.4.3的函数回调逻辑有一点复杂

**Comment by kihlh** [comment]
已修复  将在https://github.com/kihlh/hmc-win32/issues/42 解决时同步发布

**Comment by kihlh** [comment]
此问题在 1.4.6 中已经解决并发布   并修正返回值 为数字或者null
