### ISSUE TITLE
v1.4.9，getProcessName2，getProcessFilePath2，获取不存在的进程

### ISSUE THREAD

**Issue by xianyunleo** [kihlh/hmc-win32#54]
经过多次测试，Windows提供的tcp list api，可能会有残留pid。实际在进程中并不存在。
getProcessFilePath2结果是\Device\HarddiskVolume开头，应该与此有关。
希望改进：pid不存在，name和path，返回null或者空字符串

![微信图片_20240122124630](https://github.com/kihlh/hmc-win32/assets/104482255/4b5b05f4-05ee-413e-92d4-caa4b3172beb)
![微信图片_20240122124647](https://github.com/kihlh/hmc-win32/assets/104482255/6cae459b-6e8a-4d2b-bef9-1afc37b6da5a)
![微信图片_20240122124638](https://github.com/kihlh/hmc-win32/assets/104482255/84e652e7-f606-47aa-ac5e-df154568ce78)
![微信图片_20240122124643](https://github.com/kihlh/hmc-win32/assets/104482255/77d50cc5-9955-45ab-a033-5b956ba0a86c)

**Comment by kihlh** [comment]
hmc 除了对进程4与40与80 (80以内进程 都归属内核) 除了这些id以外都是实时获取的，( 虽然hmc用了很多奇淫技巧 实现获取 但是这个数据并不是杜撰出来的 )  因为他有可能是服务进程或者是系统权限，他的用户组受保护导致了进程快照列表中无法显示，而Get-Proces调用的实际上是内核进程快照
 
**他唯一的获取内容错误可能只有进程在获取完之前就已经退出了 或者获取到了以后就退出了 **

getProcessFilePath2 的逻辑是打开进程句柄 如果进程不存在这个句柄也是不存在的
![image](https://github.com/kihlh/hmc-win32/assets/62889891/ca3f9512-4029-488e-832b-3e76ae5ec01d)
而获取失败后取其名称调用的也是快照和内核快照 所以他大概率是存在的

举个例子
![image](https://github.com/kihlh/hmc-win32/assets/62889891/20486811-0b0e-46f4-92d9-78d0adbb1c66)

**Comment by xianyunleo** [comment]
你的说法，我看不太懂。
至于我的openArk截图，我补充一下，我的那个进程在 openArk “进程”列表里也是找不到的。
至于我在openArk的“网络管理”里截图有进程路径，我觉得是 openArk 处理的不对。

现在的情况是windows tcp list api 的这个pid在进程里不存在。
c#和powershell的返回和系统任务管理器查看不到是最好的解释。
或者说c#和powershell的返回等，是正确的处理方式，是正确的返回结果。

附上systeminformer对这种情况的处理，icon没有正确获取到，行背景还特地标上暗红色。它的进程列表也没有此pid。
![21](https://github.com/kihlh/hmc-win32/assets/104482255/f978ac4c-a31b-46ad-8800-4e2ddd5ffd90)
![22](https://github.com/kihlh/hmc-win32/assets/104482255/af1238c2-28ba-4c74-b1d6-a99175c4b617)

**Comment by kihlh** [comment]
十分感谢您的反馈 但我还是认为这个进程有可能是以服务的方式或者依附于某个系统应用进行提权了，由于这个进程比较特殊不可用被系统忽略，而Volume路径获取到只有两种可能，因为可以用于端口的进程可以很多种

1. 获取普通路径失败 获取的镜像路径
2. 这是个服务进程（您反馈的此进程可能是如此）
3. 进程以一种类似挂起的方式存在

但是你这个反馈似乎可以有一个更加合理的解决方式
- 增加一个配置对象 对获取内容进行细分
 - 获取不到的时候是否使用内核名称（默认启用）
 - 如果可以获取服务进程 （默认不启用）
 - 只对进程列表存在的pid获取 （默认启用）

**Comment by xianyunleo** [comment]
我上图的php-fpm进程，实际是一个cmd控制台进程，而非注册了Windows服务的进程。
是由于我循环启动、关闭操作产生的。所以猜它可能是残留进程。

操作系统对于这类进程的内部处理我不清楚。

但是目前微软c#和powershell对于此类进程是返回null的

我希望hmc-win32对这类进程的name和path返回也默认null
而net-win32的tcp列表保留此类pid（目前很多工具都保留了，如 netstat 命令也有的）
