### ISSUE TITLE
这段逻辑是错的。opacity > -1 || opacity < 255

### ISSUE THREAD

**Issue by wuchuguang** [kihlh/hmc-win32#63]
setTransparent(opacity) {
    if (opacity > -1 || opacity < 255) {
      throw new Error(
        "fun <setTransparent> arg:<Opacity> is only allowed from -1 to 255"
      );
    }

**Comment by wuchuguang** [comment]
要改为： opacity < 0 || opacity  > 255

**Comment by kihlh** [comment]
感谢反馈，下个版本中解决，您可以直接修改js

**Comment by kihlh** [comment]
√ 已修改 将在下个版本中得到修复
