### ISSUE TITLE
lookHandleShowWindow 的C++源码没找到

### ISSUE THREAD

**Issue by wuchuguang** [kihlh/hmc-win32#64]
lookHandleShowWindow(handle, 0) 后，
父进程关闭后，隐藏后的这个handle的窗体不会跟着关闭。

**Comment by kihlh** [comment]
C++代码重构比例超过300%，模块化了，我也不清楚在哪里，按照我的记忆 名字应该改成了SetShowWindow...，反正都在hmc_window.cpp里

**Comment by kihlh** [comment]
lookHandleShowWindow / SetShowWindow 和源代码没关系这个是直接调用winapi的 [showWindow](https://learn.microsoft.com/zh-cn/previous-versions/aa932387(v=msdn.10)?redirectedfrom=MSDN) 在任何版本下都是没有中间商赚差价的

**父进程关闭后，隐藏后的这个handle的窗体不会跟着关闭**  这个和hmc无关，可能是你控制的软件的窗口句柄管理逻辑设计问题
