### ISSUE TITLE
强制关闭应用的函数没有考虑应用可能退出二次确认的情况

### ISSUE THREAD

**Issue by dongfangbai-a** [kihlh/hmc-win32#65]
遇到一个情况，调用正常关闭窗口的函数HWND.close()，应用并不做任何响应，只能调用强制关闭函数HWND.closed() 或者HMC.closedHandle()，但是应用还有二次确认弹窗，而现在的强制关闭函数会阻塞进程直到应用关闭为止，就导致node进程假死在关闭函数处，js再也无法往下运行，是否可以提供一个带回调函数的关闭函数，应用真正关闭后再触发回调函数。

**Comment by kihlh** [comment]
这个逻辑是正确的，win32允许这样做，如果需要强制关闭进程请用句柄获取pid然后kill掉，如果只是销毁窗口可以销毁线程

**Comment by kihlh** [comment]
好主意这个函数可以做成 微任务(async)

**Comment by dongfangbai-a** [comment]
我的情况是，应用必须走正常的退出逻辑来尽可能保证应用退出前完成一些必要工作，如果直接kill掉，我希望的这部分工作将无法完成。如果能有一个带回调的关闭函数，逻辑上就可以兼容我遇到的这种情况。

**Comment by kihlh** [comment]
于 1.4.92 版本中的到修复 此问题合并到 https://github.com/kihlh/hmc-win32/issues/67
