### ISSUE TITLE
`node_modules/hmc-win32/hmc.d.ts(3215,17): error TS2708: Cannot use namespace 'HMC' as a value.`

### ISSUE THREAD

**Issue by JellyBrick** [kihlh/hmc-win32#7]
![image](https://github.com/kihlh/hmc-win32/assets/16558115/8e1ff05b-7763-4c1f-9758-280fc0bb40a7)

```typescript
HMC: typeof HMC;
```

TS2708: Cannot use namespace 'HMC' as a value.

**Comment by kihlh** [comment]
HMC: typeof HMC;" is TypeScript's own analysis and addition. You can directly remove the "HMC" type from the hmc object. This issue will be addressed in the next version.

**Comment by kihlh** [comment]
The solution to this problem has been supported in version 1.3.7.
