### ISSUE TITLE
网络模块功能

### ISSUE THREAD

**Issue by qian-jiang** [kihlh/hmc-win32#70]
测试网络模块的api，提示方法方法不存在。
只有isAdmin一个方法可用。

win10  22H2，node：v16.20.2

**Comment by qian-jiang** [comment]
打印HMC，网络模块也有很多api不存在。这里是暂未实现吗，或者是对系统有其他的兼容性要求

**Comment by kihlh** [comment]
他被独立出来了，因为网络相关的是个大类，微软的很多相关功能引用会导致编译冲突
他叫做 net-win32

详见
https://github.com/kihlh/hmn-win32

**Comment by qian-jiang** [comment]
> 他被独立出来了，因为网络相关的是个大类，微软的很多相关功能引用会导致编译冲突 他叫做net-win32
> 
> 详见 https://github.com/kihlh/hmn-win32

了解，多谢大佬
