### ISSUE TITLE
HMC::HMC current method only supports win32 platform

### ISSUE THREAD

**Issue by Iffyyy** [kihlh/hmc-win32#72]
![image](https://github.com/user-attachments/assets/0521675f-fa7f-45f5-99b8-2dc58008acc4)
i got the error，but process.platform already is win32

**Comment by kihlh** [comment]
可以询问下当前
平台和构架  是什么嘛

以及他有没有被打包，bin/下文件是否包含
hmc_x64.node，  hmc_x86.node

**Comment by Iffyyy** [comment]
> 可以询问下当前 平台和构架 是什么嘛
> 
> 以及他有没有被打包，bin/下文件是否包含 hmc_x64.node， hmc_x86.node



> 可以询问下当前 平台和构架 是什么嘛
> 
> 以及他有没有被打包，bin/下文件是否包含 hmc_x64.node， hmc_x86.node

electron项目里，有.node文件
![image](https://github.com/user-attachments/assets/e9b5afa0-a002-41aa-88ac-bdd7f46423bc)

**Comment by kihlh** [comment]
什么构架  process.arch   的值

**Comment by Iffyyy** [comment]
> 什么构架 process.arch 的值

ia32，有执行require("./bin/HMC_x86.node")，但是我看这里抛异常了
![image](https://github.com/user-attachments/assets/0cfc485b-52a9-42d1-a5d8-ad5227120299)

**Comment by Iffyyy** [comment]
> 可以询问下当前 平台和构架 是什么嘛
> 
> 以及他有没有被打包，bin/下文件是否包含 hmc_x64.node， hmc_x86.node
electron版本是1.8.7

![image](https://github.com/user-attachments/assets/519fe500-004b-4753-a2ca-71835cac0857)

**Comment by kihlh** [comment]
1.8.7  还是 18.7  ？     如果是1.8.7是不支持的因为他可能不支持napi(node-api c语言)          napi要求是最低node12

**Comment by Iffyyy** [comment]
> 1.8.7 还是 18.7 ？ 如果是1.8.7是不支持的因为他可能不支持napi(node-api c语言) napi要求是最低node12

1.8.7，好的了解了，感谢解答
