### ISSUE TITLE
是不是代码不全

### ISSUE THREAD

**Issue by devhub126** [kihlh/hmc-win32#73]
如题

**Comment by kihlh** [comment]
什么问题，

整个模块功能代码都是齐全的，只是有些接口没有参考价值(代码能跑就不修了，工程量超过我预期了)

**Comment by devhub126** [comment]
![PixPin_2024-09-04_10-50-49](https://github.com/user-attachments/assets/e39dadf0-6fa9-42d1-89ca-da195c0ffadf)
binding.gyp内的文件清单和代码目录里不一致，导致不能正常编译

**Comment by kihlh** [comment]
现在是用vs编译的，命令行编译太慢了要接近两分钟，vs热编译只要几秒，还能断点调试

配置文件在:  https://github.com/kihlh/hmc-win32/tree/master/source%2FCPP%2Fmsvc

**Comment by devhub126** [comment]
能不能给点指导，
![PixPin_2024-09-04_11-01-19](https://github.com/user-attachments/assets/253cb587-aab9-4fbe-bad1-43c293280703)
napi开发的设置，网上资料太少了，没有趁手的IDE，让项目工程化，总感觉乱乱的

**Comment by kihlh** [comment]
https://github.com/kihlh/hmc-win32/blob/master/source/CPP/msvc/binding.sln

binding.sln拖进vs直接就是完整的工程状态了


配置的话我得晚点回去看看

**Comment by kihlh** [comment]
**配置文件已经更新 可以直接使用node-gyp rebuild 指令编译**

详见开发帮助文档 ：https://github.com/kihlh/hmc-win32/blob/master/%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97.md
